version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    restart: unless-stopped
    volumes:
      - ".:/app"
    ports:
      - "5174:5174" # Memetakan port dari kontainer ke host
    environment:
      - VITE_PORT=5174 # Menentukan port Vite
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/
      && npm run dev"

  prod:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    restart: unless-stopped
    volumes:
      - ".:/app"
    ports:
      - "5174:5174" # Memetakan port dari kontainer ke host
    environment:
      - VITE_PORT=5174 # Menentukan port Vite
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/
      && npm run dev"
